# Generated by Django 6.0.4 on 2026-07-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_current_user',
            field=models.BooleanField(default=0),
        ),
    ]
