# Generated by Django 6.0.4 on 2026-07-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
